create table teachers(
  teacher_id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  name text 
);

create table students(
  student_id bigint generated by default as identity primary key,
  name text not null,
  face_embedding json,
  voice_embedding json
);

create table subjects(
  subject_id bigint generated by default as identity primary key,
  subject_code text not null,
  name text default 'UNKNOWN',
  section text default 'N/A',
  teacher_id bigint references teachers
    (teacher_id) on delete set null
);

create table subject_students(
  subject_id bigint references subjects
    (subject_id) on delete cascade,
  student_id bigint references students
    (student_id) on delete cascade,
  primary key(subject_id, student_id)
);

create table attendence_logs(
  id bigint generated by default as identity primary key,
  timestamp timestamptz default now(),
  subject_id bigint references subjects
    (subject_id) on delete cascade,
  student_id bigint references students
    (student_id) on delete cascade,
  is_present boolean default false

);